style(all) auto format with shfmt

diff --git a/confirm b/confirm
--- a/confirm
+++ b/confirm
@@ -13,23 +13,22 @@
 MESSAGE="${1:-Do you wish to continue? (Y/y): }"
 
 reply() {
-  if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
-    exit 0
-  else
-    exit 1
-  fi
+	if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
+		exit 0
+	else
+		exit 1
+	fi
 }
 
 if [ -n "$(${SHELL} -c 'echo ${ZSH_VERSION}')" ]; then # Zsh prompt
-  echo -ne "${MESSAGE}"
-  read REPLY
-  reply
+	echo -ne "${MESSAGE}"
+	read REPLY
+	reply
 elif [ -n "$(${SHELL} -c 'echo ${BASH_VERSION}')" ]; then # Bash prompt
-  echo -ne "${MESSAGE}"
-  read -r
-  reply
+	echo -ne "${MESSAGE}"
+	read -r
+	reply
 else
-  echo -e "ERROR: Shell not suported" >&2
-  exit 2
+	echo -e "ERROR: Shell not suported" >&2
+	exit 2
 fi
-
